Added support for Polarberry
polarfire-soc/u-boot pull request #2
Opened 2023-09-20 23:36 UTC by Mans-sdsp

Support for Polarberry added to the 2023.07.next branch

2023-09-28 09:15 UTC, ConchuOD requested changes
Hey Mans,

Apologies for the delay, been busy with release activities unfortunately.
I've left some comments, mainly on the devicetree, but overall this looks pretty good to me.

Thanks,
Conor.

2023-09-28 09:15 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	model = "Microchip POLARBERRY";
It's a sundance polarberry, not a microchip polarberry, right?

2023-09-28 09:15 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	compatible = "microchip,mpfs";
You need to add a board-specific compatible here. You can check the linux repo & use the one listed there for the polarberry.

2023-09-28 09:15 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	// 0x72 = SI538A-B-GM
What does this comment refer to?

2023-09-28 09:15 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	uboot,dm-pre-reloc;
These u-boot specific bits look like they should be in sundancedsp_polarberry-u-boot.dtsi

2023-09-28 09:15 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	local-mac-address = [56 34 00 FC 00 03];
Why is a fixed mac address being set in the dts? It looks like you have included the code in your platform that will create a mac address at runtime depending on board serial number?

2023-09-28 09:15 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	xlnx,usb-reset-mode = <0x2>;
What affect do these xlnx vendor properties have on our usb controller?

2023-09-28 09:15 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +/dts-v1/;
re: the filename, can you call it "mpfs-polarberry.dts" please? I know the icicle file has the vendor in the name, but we're moving away from that at the moment, and have moved most of the boards to having no vendor in the name. In upstream u-boot, the ones prefixed by "microchip" have had that removed, and next time we bump the version of our vendor u-boot the vendor prefixes will vanish.

2023-10-10 17:28 UTC, Mans-sdsp commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	compatible = "microchip,mpfs";
Hello Conor, 
Can you please elaborate? Polarberry is compatible with Microchip, mpfs, what do we put here?
Kisn regards

2023-10-11 12:59 UTC, ConchuOD commented on arch/riscv/dts/sundancedsp_polarberry.dts
> +	compatible = "microchip,mpfs";
https://github.com/linux4microchip/linux/blob/linux-6.1-mchp/arch/riscv/boot/dts/microchip/mpfs-polarberry.dts#L14

2023-10-19 23:38 UTC, Mans-sdsp commented
Hello Conor,
   The requested changes were implemented and tested. Please check the PR and merge it if there are no other comments so we can start working on Buildroot PR.

2023-10-24 12:09 UTC, ConchuOD requested changes
I left a couple of comments on the dts, but could you also rebase/squash this PR so that it is a single commit?
I'd be happy to merge this once those are resolved.

2023-10-24 12:09 UTC, ConchuOD commented on arch/riscv/dts/mpfs-polarberry.dts
> +	compatible = "microchip,mpfs";
Please use         `compatible = "sundance,polarberry", "microchip,mpfs";` like the linux devicetree

2023-10-24 12:09 UTC, ConchuOD commented on arch/riscv/dts/mpfs-polarberry.dts
> +//	local-mac-address = [56 34 00 FC 00 03];
Please remove these comments, the DT is not a suitable place for explaining how to use properties. You've included the code that will populate the mac address as an environment variable, based on the serial number of the SoC.
Either the contents of the environment variable, or a user-controlled value, can be set as the mac address in the u-boot console.

2023-10-24 17:30 UTC, Mans-sdsp commented
Hello Conor, I made all the required changes. Please check it.

2023-10-26 16:35 UTC, Mans-sdsp commented
it seems it is not merged yet!

2023-10-26 16:36 UTC, Mans-sdsp commented
@ConchuOD It doesn't seem to be merged.

2023-10-27 08:15 UTC, ConchuOD commented
> @ConchuOD It doesn't seem to be merged.

I'm not sure that I understand - you closed and reopened this PR several times over the last few days, but none of them contained any commits as far as I can tell. Please check that you pushed the right branch back to github after you did your rebase.

Cheers,
Conor.

2023-10-27 19:06 UTC, Mans-sdsp commented
It is very strange! Please see the changes.

2023-10-31 09:42 UTC, merged

2023-10-31 09:43 UTC, ConchuOD commented
> It is very strange! Please see the changes.

That looks a lot better, thanks!